stages:
  - build
  - deploy

build:
  stage: build
  image: node:16-alpine
  script:
    - npm install          
    - npm run build          
  artifacts:
    paths:
      - dist/                

deploy:
  stage: deploy
  image: node:16-alpine
  script:
    - npm install --production   
    - npm start                  
  environment:
    name: production
    url: http://35.154.235.73:3000 
  only:
    - main
