stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - docker
  script:
    - mkdir -p ~/.ssh
    - echo "$EC2_PEM_KEY" > ~/.ssh/ec2-key.pem
    - chmod 600 ~/.ssh/ec2-key.pem
    - ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem ec2-user@<35.154.235.73 '
        cd /home/ec2-user/node-app &&
        git pull git@gitlab.com:node-app/node-app.git &&
        docker-compose down &&
        docker-compose up -d'
  only:
    - main
