stages:
  - build
  - deploy

# Build Job
build:
  image: docker:latest
  stage: build
  services:
    - docker:dind  # Docker-in-Docker service to build the Docker image
  script:
    - docker build -t node_app .  # Build the Docker image
    - docker-compose up -d  # Run the application using Docker Compose
  only:
    - main  # Only trigger this job on the master branch

# Deploy Job
deploy:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  script:
    - docker-compose down  # Stop any existing containers
    - docker-compose up -d  # Deploy the new containers
  only:
    - main  # Only trigger this job on the master branch
