stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
  - echo "Logging into Docker registry"
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - echo "Building Docker image"
    - docker-compose -f docker-compose.yml build
  only:
    - main  # or the branch you want to trigger this job

test:
  stage: test
  script:
    - echo "Running tests in Docker container"
    - docker-compose -f docker-compose.yml run --rm app npm test
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying application"
    - docker-compose -f docker-compose.yml up -d
  only:
    - main
