version: '3.8'

services:
  nodejs-app:
    image: shwethagowda16/node-sample-app:latest  # Use the image pushed to Docker Hub
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
      placement:
        constraints:
          - node.role == worker  # Ensure replicas are deployed on worker nodes
    volumes:
      - nodejs-app-data:/usr/src/app

volumes:
  nodejs-app-data:
