version: '3.8'

services:
  nodejs-app:
    image: nodejs-app  # Image will be built during the Jenkins pipeline process
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    deploy:
      replicas: 3  # Set the number of replicas to 3
      resources:
        limits:
          cpus: '0.5'  # Limit to 0.5 CPU
          memory: 500M  # Limit to 500MB of memory
      placement:
        constraints:
          - node.role == worker  # Ensure that the containers are scheduled on worker nodes only
    networks:
      - app-network  # Connect the service to a network

networks:
  app-network:
    driver: overlay  # Use overlay network for inter-container communication across Swarm nodes
