name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy Files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/node-app

    - name: Run Docker Compose on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        cd ~/node-app
        docker-compose down
        docker-compose up -d --build
        EOF
